import { describe, expect, it } from "vitest";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { appendGeneratedByFooter } from "../src/utils/markdown";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");

describe("abud.fun ownership and attribution", () => {
  it("package.json author includes Abed and abud.fun", () => {
    const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, "package.json"), "utf8"));
    expect(pkg.author).toContain("Abed");
    expect(pkg.author).toContain("abud.fun");
    expect(pkg.repository.url).toContain("3bud-ZC/RepoRadar-Ai");
    expect(pkg.bugs.url).toContain("3bud-ZC/RepoRadar-Ai");
    expect(pkg.homepage).toContain("3bud-ZC/RepoRadar-Ai");
  });

  it("LICENSE exists and contains the correct copyright line", () => {
    const licensePath = path.join(rootDir, "LICENSE");
    expect(fs.existsSync(licensePath)).toBe(true);
    const license = fs.readFileSync(licensePath, "utf8");
    expect(license).toContain("Copyright (c) 2026 Abed — abud.fun");
    expect(license).toContain("MIT License");
  });

  it("README contains Author & Ownership section", () => {
    const readme = fs.readFileSync(path.join(rootDir, "README.md"), "utf8");
    expect(readme).toContain("## Author & Ownership");
    expect(readme).toContain("Abed");
    expect(readme).toContain("abud.fun");
    expect(readme).toContain("3bud-ZC");
  });

  it("generated markdown reports contain the footer", () => {
    const outputDir = path.join(rootDir, "examples", "sample-project-output");
    const markdownFiles = fs.readdirSync(outputDir).filter((f) => f.endsWith(".md"));
    expect(markdownFiles.length).toBeGreaterThan(0);

    for (const file of markdownFiles) {
      const content = fs.readFileSync(path.join(outputDir, file), "utf8");
      expect(content, `Missing footer in ${file}`).toContain("Generated by **RepoRadar AI**");
      expect(content, `Missing attribution in ${file}`).toContain("Built by **Abed** for **abud.fun**");
      expect(content, `Missing repo link in ${file}`).toContain("https://github.com/3bud-ZC/RepoRadar-Ai");
    }
  });

  it("repo-facts.json does NOT contain markdown footer", () => {
    const jsonPath = path.join(rootDir, "examples", "sample-project-output", "repo-facts.json");
    const content = fs.readFileSync(jsonPath, "utf8");
    expect(content).not.toContain("Generated by **RepoRadar AI**");
    expect(content).not.toContain("Built by **Abed** for **abud.fun**");
  });

  it("CLI help contains attribution", () => {
    const helpOutput = execSync("node dist/cli.js --help", { cwd: rootDir, encoding: "utf8" });
    expect(helpOutput).toContain("RepoRadar AI");
    expect(helpOutput).toContain("abud.fun");
    expect(helpOutput).toContain("3bud-ZC/RepoRadar-Ai");
  });

  it("there is exactly one STATUS.md in the project root", () => {
    const rootFiles = fs.readdirSync(rootDir);
    const statusFiles = rootFiles.filter((f) => f.toLowerCase().includes("status") && f.endsWith(".md"));
    expect(statusFiles.length).toBe(1);
    expect(statusFiles[0]).toBe("STATUS.md");
  });

  it("appendGeneratedByFooter adds footer exactly once", () => {
    const input = "# Hello\n\nSome content.";
    const withFooter = appendGeneratedByFooter(input);
    expect(withFooter).toContain("Generated by **RepoRadar AI**");
    expect(withFooter).toContain("Built by **Abed** for **abud.fun**");
    expect(withFooter).toContain("https://github.com/3bud-ZC/RepoRadar-Ai");

    const withFooterAgain = appendGeneratedByFooter(withFooter);
    expect(withFooterAgain).toBe(withFooter);
  });
});
