import type { ImprovementItem, RepoFacts } from "../types/repoFacts";

function labels(item: ImprovementItem): string {
  const parts = ["repo-radar", item.category, item.severity, item.effort];
  return parts.join(", ");
}

function renderIssue(item: ImprovementItem, index: number): string {
  const lines: string[] = [
    `## Issue ${index + 1}: ${item.title}`,
    "",
    `**Labels:** ${labels(item)}`,
    "",
    "### Problem",
    item.problem,
    "",
    "### Recommended Fix",
    item.recommendedFix,
    "",
    "### Acceptance Criteria",
    ...item.acceptanceCriteria.map((c) => `- [ ] ${c}`),
    "",
    "### Suggested Files",
    ...item.suggestedFiles.map((f) => `- ${f}`),
    "",
    "### Notes",
    `Generated by RepoRadar AI based on deterministic scan facts. Safe for agent: ${item.safeForAgent ? "Yes" : "Review manually first"}.`,
    "",
  ];
  return lines.join("\n");
}

export function generateGitHubIssues(repoFacts: RepoFacts): string {
  const items = repoFacts.improvementItems;

  const lines: string[] = [
    `# GitHub Issues Export: ${repoFacts.metadata.projectName}`,
    "",
    "Copy-paste each issue into GitHub. Labels are suggested; adjust them to match your repo's label conventions.",
    "",
    `**Total issues:** ${items.length}`,
    `**Critical:** ${items.filter((i) => i.severity === "critical").length}`,
    `**Warnings:** ${items.filter((i) => i.severity === "warning").length}`,
    `**Info:** ${items.filter((i) => i.severity === "info").length}`,
    "",
  ];

  if (items.length === 0) {
    lines.push("No issues were identified. The scan did not detect actionable improvements.");
  } else {
    for (let i = 0; i < items.length; i++) {
      lines.push(renderIssue(items[i], i));
    }
  }

  lines.push("---");
  lines.push("*Generated by RepoRadar AI*");

  return lines.join("\n");
}
