import type { RepoFacts } from "../types/repoFacts";
import { bulletList, orderedList, section } from "../utils/markdown";

export function generateReadmeSuggestion(repoFacts: RepoFacts): string {
  const languageSummary = repoFacts.detectedLanguages.map((language) => `${language.name} (${language.fileCount})`);
  const envNames = [...new Set(repoFacts.architecture.envUsage.map((usage) => usage.name))];
  const routeSummary = repoFacts.architecture.routes.map((route) => `${route.method ?? "unknown"} ${route.path}`);
  const structureSummary = repoFacts.architecture.layers.map(
    (layer) => `${layer.name}: ${layer.files.slice(0, 4).join(", ") || "none detected"}`,
  );
  const setupSteps = [
    repoFacts.monorepo.isMonorepo
      ? `Install dependencies with the root workspace manager (${repoFacts.monorepo.workspaceManager ?? "detected workspace tooling"}).`
      : "Install dependencies with the detected package manager.",
    "Create local environment variables from `.env.example` if the project uses runtime config.",
    "Run the documented dev, build, and test commands.",
  ];
  if (repoFacts.ecosystems.python.detected) {
    setupSteps.splice(1, 0, "Install Python dependencies from requirements.txt, pyproject.toml, or Pipfile as appropriate.");
  }

  return [
    `# ${repoFacts.metadata.projectName}`,
    "",
    `Draft README generated by RepoRadar AI for a ${repoFacts.projectType} repository.`,
    "",
    section(
      "What This Project Does",
      `This repository appears to be a ${repoFacts.projectType} built with ${repoFacts.detectedFrameworks.join(", ") || "an undetected stack"}.`,
    ),
    section(
      "Tech Stack",
      bulletList([
        `Languages: ${languageSummary.join(", ") || "not detected"}`,
        `Frameworks and tools: ${repoFacts.detectedFrameworks.join(", ") || "none detected"}`,
        `Package manager: ${repoFacts.packageManager ?? "not detected"}`,
        `Monorepo: ${repoFacts.monorepo.isMonorepo ? "yes" : "no"}`,
      ]),
    ),
    section(
      "Architecture",
      bulletList([
        `Architecture style: ${repoFacts.architecture.architectureStyle}`,
        `Entrypoints: ${repoFacts.architecture.entrypoints.map((entrypoint) => entrypoint.file).join(", ") || "none detected"}`,
        `Layers: ${repoFacts.architecture.layers.map((layer) => layer.name).join(", ") || "none detected"}`,
        `Dependency summary: ${repoFacts.dependencyGraph.internalEdges.length} internal edges, ${repoFacts.dependencyGraph.externalPackages.length} external packages`,
        `Alias patterns: ${repoFacts.architecture.moduleResolution.aliases.map((alias) => alias.pattern).join(", ") || "none detected"}`,
      ]),
    ),
    section("Workspace Layout", bulletList(repoFacts.monorepo.monorepoNotes)),
    section(
      "Suggested Setup Steps",
      orderedList(setupSteps),
    ),
    section(
      "Environment Variables",
      bulletList(envNames.map((name) => `${name}`)),
    ),
    section(
      "Project Structure",
      bulletList(structureSummary),
    ),
    section(
      "API And Routes",
      bulletList([
        ...routeSummary,
        `Health endpoints: ${repoFacts.hasHealthEndpoint ? repoFacts.detectedHealthRoutes.join(", ") : "none detected"}`,
      ]),
    ),
    section(
      "Testing And Deployment Notes",
      bulletList([
        `Tests detected: ${repoFacts.qualitySignals.hasTests ? "yes" : "no"}`,
        `Deployment tools: ${repoFacts.deployment.tools.join(", ") || "none detected"}`,
        `CI providers: ${repoFacts.ci.providers.join(", ") || "none detected"}`,
      ]),
    ),
    section(
      "RepoRadar Config And Scan Notes",
      bulletList([
        `Config detected: ${repoFacts.config.configDetected ? "yes" : "no"}`,
        `Output directory: ${repoFacts.config.outputDir}`,
        `Alias config files: ${repoFacts.architecture.moduleResolution.configFiles.join(", ") || "none"}`,
        `Scan truncated: ${repoFacts.scanSafety.truncated ? "yes" : "no"}`,
        `Skipped files/folders: ${repoFacts.scanSafety.skippedFiles}/${repoFacts.scanSafety.skippedFolders}`,
      ]),
    ),
    section("Known Gaps To Document", bulletList(repoFacts.issues)),
    section("Recommended README Additions", orderedList(repoFacts.recommendedNextSteps)),
  ].join("\n");
}
